#:schema https://creativeprojects.github.io/resticprofile/jsonschema/config-1.json
#
# indentation is not needed but it makes it easier to read ;)
#
version = "1"

[global]
  initialize = true
  # prevent idle sleeping
  prevent-sleep = true

[default]
  description = "Restic backup of user timotheos  on host mack"
  repository = "rclone:b2:mack-timotheos"
  option = [
    "rclone.args=serve restic --stdio --b2-hard-delete --fast-list --verbose",
  ]
  password-file = "../sops-nix/secrets/users/timotheos/restic_b2_mack-timotheos"
  verbose = true

  [default.backup]
    # set to true for first run
    dry-run = true
    source = ["/Users/timotheos"]
    # set to false as "restic check" is a data intensive operation
    check-before = false
    exclude-file = "./exclude_home.txt"
    exclude-caches = true
    # SCHEDULING
    # run the backup daily at 12:30 am
    schedule = "*.*.* 00:30"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = "mack-timotheos-b2backup_{{ .Now.DateOnly }}.log"
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [[default.backup.send-before]]
      method = "HEAD"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38/start"

    [[default.backup.send-after]]
      method = "HEAD"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38"

    [default.backup.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/42a6053f-8428-43a2-bf57-5394990b3e38/fail"
      body-template = "body-template.json"

      [[default.backup.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"

  [default.forget]
    # set to true for first run
    dry-run = true
    host = "mack"
    prune = true
    keep-last = 10
    keep-daily = 7
    keep-weekly = 12
    keep-monthly = 24
    keep-yearly = 25
    # SCHEDULING
    # run a forget and prune operation on Mondays at 1:30 am
    schedule = "Mon *.*.* 01:30"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = "mack-timotheos-b2prune_{{ .Now.DateOnly }}.log"
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [default.forget.send-before]
      method = "HEAD"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50/start"

    [default.forget.send-after]
      method = "HEAD"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50"

    [default.forget.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/b14dac3a-79ae-4bac-89aa-4751c7603b50/fail"
      body-template = "body-template.json"

      [[default.forget.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"

  [default.check]
    # run an integrity check on the 1st of each month at 2 am
    schedule = "*.*.1 02:00"
    schedule-permission = "system"
    schedule-priority = "background"
    schedule-log = "mack-timotheos-b2check_{{ .Now.DateOnly }}.log"
    schedule-lock-wait = "5m"

    # send monitoring info to healthchecks.io
    [default.check.send-before]
      method = "HEAD"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682/start"

    [default.check.send-after]
      method = "HEAD"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682"

    [default.check.send-after-fail]
      method = "POST"
      url = "https://hc-ping.com/4b6b82d9-1088-4763-8129-2ce1f996b682/start"
      body-template = "body-template.json"

      [[default.check.send-after-fail.headers]]
        name = "Content-Type"
        value = "text/plain; charset=UTF-8"
